replace [0] with []
The latter has been deprecated upstream and does not work with the
bounds checking performed there. Fixes warnings such as:

error: call to '__write_overflow_field' declared with attribute warning:
detected write beyond size of field (1st parameter); maybe use
struct_group()? [-Werror=attribute-warning]
493 |                         __write_overflow_field(p_size_field, size);

Signed-off-by: Rosen Penev <rosenp@gmail.com>