Simplify coredump memcpy in mwl_fwcmd_get_fw_core_dump
Simplify coredump memcpy in mwl_fwcmd_get_fw_core_dump. Instead of doing
fragile address additions, just access the buffer member in pcmd and
reference the pointer.

This fix a compilation warning in 64Bit system:

/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/mwlwifi-2023-04-29-6a436714/hif/fwcmd.c: In function 'mwl_fwcmd_get_fw_core_dump': /home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/mwlwifi-2023-04-29-6a436714/hif/fwcmd.c:3608:31: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
3608 | (const void *)((u32)pcmd +
| ^

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>